services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  web:
    build: .
    command: puma
    volumes:
      - .:/usr/src/app/
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
    - DB_HOST=postgres
